# Generated by Django 4.0.2 on 2022-03-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PatternTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyPatterns',
        ),
        migrations.AddField(
            model_name='pattern',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.patterntable'),
        ),
    ]
