# Generated by Django 4.0.2 on 2022-03-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_pattern_patterntable_delete_mypatterns_pattern_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='table',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='PatternTable',
        ),
    ]
